// companionship -> bred primarily to be a companion dog
// working -> task-oriented breeds that need a job or mental work
// hunting -> strong prey drive; likely to chase or catch animals
// scent -> follows scent trails; nose-oriented breeds
// ratting -> bred to hunt vermin and small animals
// herding -> instinct to control and move livestock
// guarding -> instinct to protect people, property or livestock
// chasing -> sight hounds that pursue moving prey
// intense -> exceptionally demanding temperament, need for owner with experience

export const breedInstincts = {
  Affenpinscher: ["ratting"],
  "Afghan Hound": ["chasing"],
  Africanis: ["working", "guarding"],
  Aidi: ["working", "guarding"],
  "Airedale Terrier": ["hunting", "ratting", "guarding"],
  Airedoodle: ["companionship"],
  Akbash: ["guarding", "intense"],
  Akita: ["guarding", "intense"],
  "Aksaray Malaklisi": ["working", "guarding", "intense"],
  "Alano Español": ["guarding", "hunting", "intense"],
  "Alapaha Blue Blood Bulldog": ["guarding"],
  "Alaskan Husky": ["working", "intense"],
  "Alaskan Klee Kai": ["companionship"],
  "Alaskan Malamute": ["working", "guarding", "intense"],
  Alopekis: ["working", "ratting"],
  "Alpine Dachsbracke": ["hunting", "scent"],
  "American Bulldog": ["guarding"],
  "American Bully": ["companionship"],
  "American Cocker Spaniel": ["companionship"],
  "American English Coonhound": ["scent"],
  "American Eskimo Dog": ["companionship"],
  "American Foxhound": ["hunting"],
  "American Hairless Terrier": ["ratting"],
  "American Leopard Hound": ["hunting", "scent"],
  "American Pit Bull Terrier": ["guarding", "intense"],
  "American Staffordshire Terrier": ["guarding", "intense"],
  "American Water Spaniel": ["companionship"],
  "Andalusian Terrier": ["ratting", "hunting"],
  "Anglo-Français de Petite Vénerie": ["scent"],
  "Appenzeller Sennenhund": ["guarding"],
  "Argentine Pila": ["companionship"],
  Ariégeois: ["scent"],
  "Ariège Pointer": ["hunting"],
  Armant: ["herding", "guarding"],
  "Armenian Gampr": ["guarding", "intense"],
  "Artois Hound": ["scent"],
  Aussiedoodle: ["herding", "companionship"],
  "Australian Cattle Dog": ["herding", "intense"],
  "Australian Kelpie": ["herding", "intense"],
  "Australian Shepherd": ["herding"],
  "Australian Silky Terrier": ["ratting"],
  "Australian Stumpy Tail Cattle Dog": ["herding"],
  "Australian Terrier": ["ratting"],
  "Austrian Black and Tan Hound": ["scent"],
  "Austrian Pinscher": ["ratting", "companionship"],
  Azawakh: ["chasing"],
  "Bắc Hà": ["working"],
  "Bakharwal Dog": ["guarding"],
  "Banjara Hound": ["chasing"],
  "Bankhar Dog": ["guarding"],
  "Barak Hound": ["scent"],
  "Barbado da Terceira": ["herding"],
  Barbet: ["companionship"],
  Basenji: ["hunting"],
  "Basque Shepherd Dog": ["herding"],
  Bassador: ["companionship"],
  "Basset Artésien Normand": ["scent"],
  "Basset Bleu de Gascogne": ["scent"],
  "Basset Fauve de Bretagne": ["scent"],
  "Basset Hound": ["working", "scent"],
  Bassettoodle: ["companionship"],
  "Bavarian Mountain Hound": ["working", "scent"],
  Beagle: ["scent"],
  "Beagle-Harrier": ["scent", "hunting"],
  "Bearded Collie": ["herding"],
  Beauceron: ["herding", "guarding", "intense"],
  "Bedlington Terrier": ["ratting"],
  "Belgian Laekenois": ["herding", "guarding", "intense"],
  "Belgian Malinois": ["herding", "guarding", "intense"],
  "Belgian Shepherd": ["herding", "guarding", "intense"],
  "Belgian Tervuren": ["herding", "guarding", "intense"],
  "Bergamasco Sheepdog": ["working"],
  "Berger Picard": ["herding"],
  Bernedoodle: ["companionship"],
  "Bernese Mountain Dog": ["working"],
  "Bichon Frisé": ["companionship"],
  "Biewer Terrier": ["companionship"],
  Billy: ["scent"],
  "Black and Tan Coonhound": ["hunting", "scent"],
  "Black Mouth Cur": ["working", "intense"],
  "Black Norwegian Elkhound": ["hunting"],
  "Black Russian Terrier": ["working", "guarding", "intense"],
  Bloodhound: ["working", "scent"],
  "Blue Picardy Spaniel": ["companionship"],
  "Bluetick Coonhound": ["hunting", "scent"],
  Boerboel: ["guarding", "intense"],
  "Bohemian Shepherd": ["herding"],
  "Bohemian Spotted Dog": ["companionship"],
  Bolognese: ["companionship"],
  "Border Collie": ["herding", "intense"],
  "Border Terrier": ["ratting"],
  Bordoodle: ["companionship"],
  Borzoi: ["chasing"],
  "Boston Terrier": ["companionship"],
  "Bouvier des Ardennes": ["herding"],
  "Bouvier des Flandres": ["herding", "guarding"],
  Boxer: ["working", "guarding"],
  Boxerdoodle: ["companionship"],
  "Boykin Spaniel": ["companionship"],
  "Bracco Italiano": ["working", "scent"],
  "Braque d'Auvergne": ["companionship"],
  "Braque du Bourbonnais": ["companionship"],
  "Braque Français": ["companionship"],
  "Braque Saint-Germain": ["companionship"],
  "Brazilian Terrier": ["ratting"],
  Briard: ["herding", "guarding", "intense"],
  "Briquet de Provence": ["scent"],
  "Briquet Griffon Vendéen": ["scent", "hunting"],
  Brittany: ["companionship"],
  Brittanydoodle: ["companionship"],
  Broholmer: ["guarding"],
  "Bruno Jura Hound": ["scent"],
  "Bucovina Shepherd Dog": ["guarding", "intense"],
  Bugg: ["companionship"],
  "Bulgarian Hound": ["hunting"],
  "Bulgarian Scenthound": ["scent"],
  "Bull Arab": ["hunting", "intense"],
  Bulldog: ["companionship"],
  Bullmastiff: ["guarding"],
  Bulloxer: ["guarding"],
  "Bull Terrier": ["intense", "guarding"],
  "Bull Terrier (Miniature)": ["intense", "ratting"],
  "Bully Kutta": ["guarding", "intense"],
  "Burgos Pointer": ["companionship"],

  "Ca de Bou": ["guarding", "intense"],
  "Cairn Terrier": ["ratting"],
  Calupoh: ["guarding", "intense"],
  "Ca Mè Mallorquí": ["hunting"],
  "Campeiro Bulldog": ["working", "guarding"],
  "Canaan Dog": ["guarding", "intense"],
  "Canadian Eskimo Dog": ["working", "intense"],
  "Can de Chira": ["herding"],
  "Can de Palleiro": ["herding", "guarding"],
  "Cane Corso": ["guarding", "intense"],
  "Cane di Oropa": ["herding"],
  "Cane Paratore": ["herding"],
  "Cantabrian Water Dog": ["working"],
  "Cão de Gado Transmontano": ["guarding", "intense"],
  "Ca Rater Mallorquí": ["ratting"],
  "Cardigan Welsh Corgi": ["herding"],
  "Carea Leonés": ["herding"],
  "Carolina Dog": ["hunting"],
  "Carpathian Shepherd Dog": ["guarding", "intense"],
  "Castro Laboreiro Dog": ["guarding", "intense"],
  "Catahoula Leopard Dog": ["working", "intense"],
  "Catalan Sheepdog": ["herding"],
  "Caucasian Shepherd Dog": ["guarding", "intense"],
  "Cavalier King Charles Spaniel": ["companionship"],
  Cavapom: ["companionship"],
  Cavapoo: ["companionship"],
  "Central Asian Shepherd Dog": ["guarding", "intense"],
  "Cesky Terrier": ["ratting"],
  "Chart Polski": ["chasing"],
  "Chesapeake Bay Retriever": ["working"],
  "Chien Français Blanc et Noir": ["scent", "hunting"],
  "Chien Français Blanc et Orange": ["scent", "hunting"],
  "Chien Français Tricolore": ["scent", "hunting"],
  Chihuahua: ["companionship"],
  "Chilean Terrier": ["ratting"],
  "Chinese Crested": ["companionship"],
  "Chinese Shar-Pei": ["guarding"],
  Chinook: ["working"],
  Chipoo: ["companionship"],
  Chippiparai: ["chasing"],
  Chiweenie: ["companionship"],
  "Chongqing Dog": ["guarding", "intense"],
  Chorkie: ["companionship"],
  Chortai: ["chasing"],
  "Chow Chow": ["guarding"],
  Chug: ["companionship"],
  "Chukotka Sled Dog": ["working", "intense"],
  "Cimarrón Uruguayo": ["guarding", "intense"],
  "Cirneco dell'Etna": ["hunting"],
  "Clumber Spaniel": ["companionship"],
  Cockapoo: ["companionship"],
  "Cocker Spaniel": ["companionship"],
  "Colombian Fino Hound": ["scent", "hunting"],
  "Continental Bulldog": ["companionship"],
  Corgipoo: ["companionship"],
  "Corsican Dog": ["guarding", "intense"],
  "Coton de Tulear": ["companionship"],
  "Cretan Hound": ["hunting"],
  "Croatian Sheepdog": ["herding"],
  "Curly-Coated Retriever": ["working"],
  "Czechoslovakian Wolfdog": ["working", "intense"],

  Dalmatian: ["working"],
  "Doberman Pinscher": ["guarding", "intense"],
  "Dogo Argentino": ["hunting", "guarding", "intense"],
  "Dutch Shepherd": ["guarding", "working"],
  "English Setter": ["scent"],
  "English Shepherd": ["herding"],
  "English Springer Spaniel": ["companionship", "scent"],
  "English Toy Terrier (Black & Tan)": ["ratting"],
  Eurasier: ["companionship"],
  "Field Spaniel": ["scent"],
  "Finnish Hound": ["companionship", "scent"],
  "Finnish Lapphund": ["herding", "guarding"],
  "Finnish Spitz": ["companionship"],
  "French Bulldog": ["companionship"],
  "German Pinscher": ["ratting", "guarding"],
  "German Shepherd": ["guarding", "working", "intense"],
  "German Shorthaired Pointer": ["hunting"],
  "Giant Schnauzer": ["guarding", "working", "intense"],
  "Glen of Imaal Terrier": ["ratting"],
  "Golden Retriever": ["companionship"],
  "Gordon Setter": ["companionship", "scent"],
  "Great Dane": ["guarding"],
  Greyhound: ["chasing"],
  Harrier: ["scent"],
  Havanese: ["companionship"],
  "Irish Setter": ["companionship", "scent"],
  "Irish Terrier": ["ratting"],
  "Irish Wolfhound": ["guarding"],
  "Italian Greyhound": ["companionship"],
  "Japanese Chin": ["companionship"],
  "Japanese Spitz": ["companionship"],
  "Kangal Shepherd Dog": ["guarding", "intense"],
  Keeshond: ["companionship"],
  "King Charles Spaniel": ["companionship"],
  Komondor: ["guarding", "intense"],
  Kooikerhondje: ["companionship", "scent"],
  Kuvasz: ["guarding", "intense"],
  "Labrador Retriever": ["companionship"],
  "Lagotto Romagnolo": ["working", "scent"],
  "Lancashire Heeler": ["herding"],
  Leonberger: ["working", "guarding"],
  "Lhasa Apso": ["companionship"],
  Maltese: ["companionship"],
  "Miniature American Shepherd": ["herding", "working"],
  "Miniature Pinscher": ["ratting"],
  "Miniature Schnauzer": ["ratting"],
  Newfoundland: ["companionship"],
  "Norfolk Terrier": ["ratting"],
  "Norwich Terrier": ["ratting"],
  "Nova Scotia Duck Tolling Retriever": ["companionship"],
  "Old English Sheepdog": ["herding"],
  "Olde English Bulldogge": ["guarding"],
  Papillon: ["companionship", "ratting"],
  Pekingese: ["companionship"],
  "Pembroke Welsh Corgi": ["herding", "companionship"],
  "Pharaoh Hound": ["hunting", "scent"],
  "Plott Hound": ["hunting", "scent"],
  Pomeranian: ["companionship", "ratting"],
  "Poodle (Miniature)": ["companionship", "scent"],
  "Poodle (Toy)": ["companionship"],
  "Presa Canario": ["guarding", "intense"],
  Pug: ["companionship"],
  Puli: ["herding", "companionship"],
  Pumi: ["herding", "companionship"],
  "Pyrenean Mountain Dog": ["guarding", "working", "intense"],
  "Rat Terrier": ["ratting"],
  "Redbone Coonhound": ["hunting", "scent"],
  "Rhodesian Ridgeback": ["hunting", "scent", "guarding"],
  Rottweiler: ["guarding", "intense"],
  "Russian Toy": ["companionship"],
  "Saint Bernard": ["companionship"],
  Saluki: ["hunting", "scent"],
  Samoyed: ["working", "herding"],
  Schipperke: ["ratting", "working"],
  "Scottish Deerhound": ["hunting", "scent"],
  "Scottish Terrier": ["ratting", "guarding"],
  "Shetland Sheepdog": ["herding", "working"],
  "Shiba Inu": ["guarding", "intense"],
  "Shih Tzu": ["companionship"],
  "Shiloh Shepherd": ["guarding", "working", "intense"],
  "Siberian Husky": ["working", "scent"],
  "Smooth Fox Terrier": ["ratting", "hunting"],
  "Soft Coated Wheaten Terrier": ["herding", "working"],
  "Spanish Water Dog": ["companionship", "scent"],
  "Spinone Italiano": ["hunting", "scent", "working"],
  "Staffordshire Bull Terrier": ["guarding", "intense"],
  "Standard Schnauzer": ["guarding", "working"],
  "Swedish Vallhund": ["herding", "companionship"],
  "Thai Ridgeback": ["guarding", "intense"],
  "Tibetan Mastiff": ["guarding", "intense", "working"],
  "Tibetan Spaniel": ["companionship"],
  "Tibetan Terrier": ["companionship", "working"],
  "Toy Fox Terrier": ["ratting", "companionship"],
  "Treeing Walker Coonhound": ["hunting", "scent"],
  Vizsla: ["hunting", "scent", "working"],
  Weimaraner: ["hunting", "scent", "working"],
  "Welsh Springer Spaniel": ["hunting", "scent", "working"],
  "West Highland White Terrier": ["ratting", "guarding"],
  Whippet: ["chasing"],
  "White Shepherd": ["guarding", "working"],
  "Wire Fox Terrier": ["ratting", "companionship"],
  "Wirehaired Pointing Griffon": ["hunting", "scent"],
  "Wirehaired Vizsla": ["hunting", "scent"],
  Xoloitzcuintli: ["guarding", "companionship"],
  "Yorkshire Terrier": ["ratting", "companionship"],
};
